### ISSUE TITLE
About the data used in your code

### ISSUE THREAD

**Issue by fshutong** [kerimcaliskan182/NavierStokesEqSolnWithPINN#1]
Hello, your PINN solution code for the N-S equation is great. However, the data you used cannot be downloaded in HPM. Could you provide the mat data?

**Comment by kerimcaliskan182** [comment]
Hello, sorry for late reply. Thanks for your feedback. I used the data from Maziar Raissi. The link is below.

[Data Link](https://github.com/maziarraissi/HPM/tree/master/Data)

**Comment by kerimcaliskan182** [comment]
Also, you can check the read me part to find how to access, and use data.
